### PR TITLE
Improve constant performance

### PR DESCRIPTION
**Pull request by dirk**
Looks like the system was doing a lot more work than necessary when assigning constants (Rubinius' built-in `const_set` and constant AST classes are a bit bloated for Fancy); this trims everything down and fixes multiple-assignment with constants (which seems to have been broken).

### CODE REVIEW

**Comment by bakkdoor** [comment]
Cool this looks good. Thanks!

**Comment by bakkdoor** [comment]
Oh please get rid of the commented out old code and maybe also move any classes defined in the tests that are only used in one test case into the test case block itself. That's how I do it in the other test files as we'll. if a class is used in more than one test then it's ok to leave it outside of the test block.

**Comment by dirk** [comment]
Okay will do. The only reason I left the classes and constant definitions outside the test cases was to make sure that top-level constant setting and resolution was working properly.

**Comment by bakkdoor** [comment]
Oh sure if that is what you're testing then leave it and maybe add a comment. Or add a special test case for that even

**Pull request merged**
