### PR TITLE
Switch to Rubinius shortcuts in Fancy compiler

### PR DESCRIPTION
**Pull request by dirk**
Follow-up from #72 because @bakkdoor is too fast. This switches back to using the `Rubinius AST`, `Rubinius Compiler`, etc. shortcuts in the Fancy compiler. Also using the idiomatic `Rubinius::ToolSet.current::TS` toolset access method that Rubinius uses internally.

### CODE REVIEW

**Comment by bakkdoor** [comment]
Hey just wondering, why the switch back?

**Comment by dirk** [comment]
With 7354b2c029345ce091be91e303c9acb5f67642bd and 94f23c4d9d0501511831020dc266bc262de01e6c I switched them back since the original change was a mistake (since it was working perfectly before). However, for those to work with rbx-2.0 84d8f2cea7c071ecba19fe33d8af4de22224abd9 and #72 need to be in place.

**Comment by dirk** [comment]
(In fewer words: carelessness. :dizzy_face: )

**Comment by bakkdoor** [comment]
ok merged it.

**Comment by bakkdoor** [comment]
travis build is failing, but that's due to it using an older version of rbx. @brixen said, he'll upload new binaries for travis tomorrow, so it should build fine then

**Comment by dirk** [comment]
Okay, cool! Is updating Fancy internals for other new Rubinius 2.0 features like doing the gem stuff right (hax right now at: https://github.com/bakkdoor/fancy/blob/84d8f2cea7c071ecba19fe33d8af4de22224abd9/boot/rbx-compiler/compiler/compiler.rb#L1) and taking advantage of some of their work with GC/locks/other-performance-stuff important?

**Comment by bakkdoor** [comment]
Sure, I'd like to stay up to date with any improvements made in Rubinius and be able to use them in Fancy. Anything concrete you had in mind? I'm not super up to date on what's new in Rubinius 2.0, but if you have anything you'd like to work on, let me know.

**Comment by dirk** [comment]
It looks like they've made some serious GC improvements, so those should be readily apparent, and there also may be some little places where tweaks can be made to take advantage of its generations (both young in frequent GC runs and mature generation in concurrent GC runs). I'm pretty sure there are new improvements in core concurrency stuff and optimizing for the JIT, so there should be a few opportunities for profiling and optimizing there too.

**Comment by bakkdoor** [comment]
OK, so I just removed some old backwards-compatibility related code and fancy now officially requires Rubinius 2.0.0 or later.

**Comment by bakkdoor** [comment]
Given https://github.com/bakkdoor/fancy/blob/master/boot/fancy_ext.rb#L21-24 wouldn't it be OK to just use the shortcut versions in the ruby code as well (as before). I find having these long class names in the code to be somewhat ugly and adding a bit too much noise.

**Comment by dirk** [comment]
Oh, huh, yeah. More late-night-coding-dumbness on my part. Find/replace has seemed to work pretty much flawlessly with catching all these.

**Comment by bakkdoor** [comment]
ok I guess I'll switch it back then.

**Comment by bakkdoor** [comment]
btw, don't worry about making mistakes. this stuff is easy to revert and git makes fixing things easy anyway. thanks for your interest in the project and let me know if there's anything you want to know / help with.

**Comment by dirk** [comment]
Hehe thanks! I'd been fiddling with Smalltalk dialects and Rubinius & other VM stuff for years, so now seemed like a good time to finally jump in. Going to see if I can find any good points for rbx-2.0 optimization tomorrow.

**Comment by bakkdoor** [comment]
Cool, if you have any questions, let me know.

**Pull request merged**
